name: Build and test

on:
  push:
  pull_request:
  schedule:
    # run daily, this refreshes the cache
    - cron: '13 2 * * *'

jobs:
  python-test:
    name: Python tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{matrix.python-version}} (without a container)
        uses: LizardByte/setup-python-action@master
        with:
          python-version: ${{matrix.python-version}}

      - name: Install python 2 dependencies
        if: ${{ matrix.python-version == '2.7' }}
        run: pip install enum

      - name: Install dependencies
        run: pip install mock pytest

      - name: Run python tests
        run: pytest scripts

  ocaml-test:
    name: Ocaml tests
    runs-on: ubuntu-20.04
    env:
      XAPI_VERSION: "v0.0.0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull configuration from xs-opam
        run: |
          curl --fail --silent https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env | cut -f2 -d " " > .env

      - name: Load environment file
        id: dotenv
        uses: falti/dotenv-action@v1.0.4

      - name: Update Ubuntu repositories
        run: sudo apt-get update

      - name: Use ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ steps.dotenv.outputs.ocaml_version_full }}
          opam-repositories: |
            xs-opam: ${{ steps.dotenv.outputs.repository }}
          dune-cache: true

      - name: Install dependencies
        run: opam install . --deps-only --with-test -v

      - name: Configure
        run: opam exec -- ./configure --xapi_version="$XAPI_VERSION"

      - name: Build
        run: opam exec -- make

      - name: Run tests
        run: opam exec -- make test

      - name: Check all code
        run: opam exec -- make check

      - name: Run stress tests
        run: opam exec -- make stresstest
        if: ${{ github.event_name == 'schedule' }}

      - name: Build SDK
        run: |
          mkdir -p /opt/xensource/sm
          wget -O /opt/xensource/sm/XE_SR_ERRORCODES.xml https://raw.githubusercontent.com/xapi-project/sm/master/drivers/XE_SR_ERRORCODES.xml
          opam exec -- make sdk

      - name: Make install smoketest
        run: |
          opam exec -- make install DESTDIR=$(mktemp -d)
          opam exec -- make install DESTDIR=$(mktemp -d) BUILD_PY2=NO

      - name: Sanity test SDK
        run: |
          opam exec -- make sdksanity

      - name: Uninstall unversioned packages and remove pins
        # This should purge them from the cache, unversioned package have
        # 'master' as its version
        run: |
          opam list | awk -F " " '$2 == "master" { print $1 }' |  xargs opam uninstall
          opam pin list | cut -f1 -d "." | xargs opam unpin

  deprecation-test:
    name: Deprecation tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate empty configuration for make to be happy
        run: touch config.mk

      - name: quality-gate
        run: make quality-gate

      # uses: tsuyoshicho/action-mypy@v3.13.0
      - uses: bernhardkaindl/action-mypy@36cb3a857d01c1bdaa2811893106c71580132d71
        with:
          filter_mode: no_filter
          setup_method: install
          setup_command: pip install mypy mock
          mypy_flags: |
            --scripts-are-modules
            --check-untyped-defs
            --allow-redefinition
            --hide-error-context
            --ignore-missing-imports
            --no-pretty
            --warn-unreachable
            --exclude ocaml/
            --exclude scripts/examples
            --exclude scripts/examples/python/monitor-unwanted-domains.py
            --exclude scripts/scalability-tests/ping-master.py
            --exclude scripts/backup-sr-metadata.py
            --exclude scripts/restore-sr-metadata.py
            --exclude scripts/nbd_client_manager.py
            --config-file mypy.ini
          target: |
            scripts/perfmon
            scripts/hfx_filename
            scripts/mail-alarm
            scripts/host-display
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

      - uses: dciborow/action-pylint@0.1.1
        with:
          filter_mode: no_filter
          glob_pattern: "scripts/*"
          pylint_args: |
            --verbose
            --disable=trailing-whitespace
            --disable=bad-indentation
            --rc .pylintrc
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
