# -------------------------------------------------------------------------
# `pre-commit` is a framework for managing and maintaining multi-language
# pre-commit hooks. The hooks are run on every commit, and can be run
# manually with `pre-commit run`. See: https://pre-commit.com/
# -------------------------------------------------------------------------
# pre-commit is run for each git push by GitHub CI. It can run
# locally as well for early feedback and automatic formatting
# like trailing whitespace removal (to be configured later):
#
## For only installing the package itself, run:
# pip3 install pre-commit
#
## For activating it as a pre-commit and pre-push hook (recommended):
# pre-commit install --hook-type pre-push --hook-type pre-commit
#
## For manually executing the pre-push hook:
# pre-commit run -av --hook-stage pre-push
#
default_stages: [commit, push]
repos:
# Recommendation for a minimal git pre-commit hook:
# https://github.com/pre-commit/pre-commit-hooks/blob/main/README.md:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: no-commit-to-branch
        name: "The master branch should be pulled only"
        args: [--branch, master]
        always_run: true
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-executables-have-shebangs
        exclude: ocaml

-   repo: local
    hooks:
    # Used by GitHub CI to test py2/py3 in different row of the test matrix:
    # eg: SKIP=py3 pre-commit run # This skips pytest3 and diff-cover3
    -   alias: py3
        id: pytest3
        name: check Python 3 unit tests to pass
        language_version: python3
        entry: env PIP_INSTALL=done scripts/unit_test/test_runner.py
        pass_filenames: false
        language: python
        types: [python]
        additional_dependencies:
        - coverage
        - diff-cover
        - future
        - mock
        - pytest<7
        - pytest-coverage
        - pytest-mock
        - pytest-pythonpath
        - pytest-timeout
        - pyyaml

-   repo: local
    hooks:
    -   id: pytest2
        language_version: python2.7
        name: check Python 2 unit tests to pass
        entry: env PIP_INSTALL=done scripts/unit_test/test_runner.py
        pass_filenames: false
        language: python
        types: [python]
        additional_dependencies:
        - coverage
        - diff-cover
        - enum # Required for Python 2.7 (is not in the standard library)
        - future # Use the alias for the new standard library in Python 2/3
        - mock # Required for Python 2.7 (does not have unittest.mock)
        - pytest<7
        - pytest-coverage
        - pytest-mock
        - pytest-pythonpath
        - pytest-timeout
        - pyyaml

# Recommendation for a minimal git pre-push hook:
# While using pre-commit yields great results, it
# is "not fast". Therefore only run it pre-push,
# (but always in GitHub CI of course):
#
# Calls ./pytype_reporter.py in a dedicated venv:
# pre-commit run -av --hook-stage push
-   repo: local
    hooks:
    -   id: pytype
        name: pytype
        entry: python3 pytype_reporter.py
        types: [python]
        stages: [push]
        verbose: true
        # This hook runs locally only when Python files change:
        language: python
        # Pytype supports running on Python 3.8 to Python3.11 currently:
        # https://google.github.io/pytype/support.html
        # If a dev's default python3 interpreter is outside that range, but
        # developers have such version installed, it can be configured here:
        # language_version: python3.11
        require_serial: true
        additional_dependencies: [pandas, pytype]
