# https://packaging.python.org/en/latest/specifications/pyproject-toml/
[project]
name = "xen-api"
requires-python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"
license = {file = "LICENSE"}
keywords = ["xen-project", "Xen", "hypervisor", "libraries"]
maintainers = [
    {name = "Christian Lindig"},
    {name = "Edwin Török"},
    {name = "Rob Hoes"},
    {name = "Pau Ruiz Safont"},
]
readme = "README.markdown"
# https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: POSIX :: Linux :: XenServer Dom0",
    "Operating System :: POSIX :: Linux :: XCP-ng Dom0",
    "Programming Language :: ML",
    "Programming Language :: Python :: Implementation :: CPython",
]

[project.urls]
homepage = "https://github.com/xapi-project/xen-api"
repository = "https://github.com/xapi-project/xen-api"

[tool.black]
line-length = 88

[tool.isort]
line_length = 88
py_version = 27
profile = "black"
combine_as_imports = true
ensure_newline_before_comments = false

[tool.mypy]
# Note mypy has no config setting for PYTHONPATH, so you need to call it with:
# PYTHONPATH="scripts/examples/python:.:scripts:scripts/plugins:scripts/examples"
files = [
    "scripts/usb_reset.py",
    "scripts/unit_tests",
]
pretty = true
error_summary = true
strict_equality = true
show_error_codes = true
show_error_context = true
# Check the contents of untyped functions in all modules by default:
check_untyped_defs = true
scripts_are_modules = true
python_version = "3.11"
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_redundant_casts = true
disallow_any_explicit = false
disallow_any_generics = true
disallow_any_unimported = true
disallow_subclassing_any = true

[tool.pytype]
inputs = [
    'scripts/*.py',
    'scripts/',
    "scripts/10resetvdis",
    "scripts/Makefile",
    "scripts/generate-iscsi-iqn",
    "scripts/hatests",
    "scripts/hfx_filename",
    "scripts/host-display",
    "scripts/mail-alarm",
    "scripts/print-custom-templates",
    "scripts/probe-device-for-file",
    "scripts/xe-reset-networking",
    "scripts/xe-scsi-dev-map",
    'scripts/examples/python',
    # Don't add, it can't do "from .XenAPI import *" afterwards:
    # 'scripts/examples/python/XenAPI',
    # Not yet ported:
    # "ocaml/message-switch/python",
    # "ocaml/idl/ocaml_backend/python",
    # "ocaml/xapi-storage/python",
]
xfail = [
    "scripts/perfmon",
    "scripts/static-vdis",
    "scripts/usb_scan.py",
    "scripts/yum",
    "scripts/yum/plugins.py",
    "scripts/examples/python/monitor-unwanted-domains.py"
]
disable = [
    'import-error',
    "pyi-error",
    "ignored-abstractmethod"
]
keepgoing = true
platform = "linux"
python_version = "3.10"
pythonpath = "scripts/examples/python:.:scripts:scripts/plugins:scripts/examples"
# pythonpath = "scripts/examples/python/XenAPI"
# ":scripts/examples/python:scripts/examples:scripts:."
# disable = ["ignored-type-comment"]
# overriding_parameter_count_checks = true
# use_enum_overlay = true