baseURL = "https://xapi-project.github.io/new-docs/"
languageCode = 'en-us'
title = 'XAPI Toolstack Developer Documentation'
disablePathToLower = true
pygmentsCodeFences = true
assetsDir = "assets"

[module]
[[module.imports]]
    path = 'github.com/xenserver-next/hugo-theme-relearn'

# The latest upstream version of hugo-theme-relearn needs hugo 0.121.0:
# https://mcshelby.github.io/hugo-theme-relearn/basics/requirements/index.html
[module.hugoVersion]
    min = "0.126.0"

# Newer Hugo needs to set the renderer to `unsafe = true` to support the raw HTML
# code that a number of pages intentionally use.
# goldmark is already the default renderer. The only change is the flag for raw HTML:
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
# Home and section pages should also have a print icon for the print view:
home = [ "HTML", "RSS", "SEARCH", "PRINT"]
section = [ "HTML", "RSS", "PRINT"]

[params]
# Enable the theme variant selector, default to auto:
themeVariant = [
    "auto",
    "zen-light",
    "zen-dark",
    "red",
    "blue",
    "green",
    "learn",
    "neon",
    "relearn-light",
    "relearn-bright",
    "relearn-dark"
]
# auto switches between "red" and "zen-dark" depending on the browser/OS dark mode:
themeVariantAuto = ["red", "zen-dark"]
alwaysopen = false
collapsibleMenu = true
