name: Build and test

on:
  push:
  pull_request:
  schedule:
    # run daily, this refreshes the cache
    - cron: "13 2 * * *"

concurrency: # On new push, cancel old workflows from the same PR, branch or tag:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-test:
    name: Python tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To check which files changed: origin/master..HEAD
      - uses: LizardByte/setup-python-action@master
        with:
          python-version: ${{matrix.python-version}}

      - uses: actions/cache@v4
        name: Setup cache for running pre-commit fast
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: echo "::add-matcher::.github/workflows/python-warning-matcher.json"
        name: "Setup GitHub for reporting Python warnings as annotations in pull request code review"

      - name: Install dependencies for the static analysis
        if: ${{ matrix.python-version != '2.7' }}
        run: >
          pip install opentelemetry-api opentelemetry-exporter-zipkin-json
          opentelemetry-sdk pytest types-mock mock wrapt pandas

      # pyright is also added as a pre-commit hook in .pre-commit-config.yaml
      # but we also run it here to get annotations in the pull request code review
      # in case the pre-commit hook is not run by the developer:
      # https://github.com/marketplace/actions/run-pyright-with-reviewdog (annotations only)
      - uses: jordemort/action-pyright@v1
        if: ${{ matrix.python-version != '2.7' }}
        with:
          level: notice  # Only at notice level (lower priority than warning)
          filter_mode: file  # Only report notices when the file is changed
          fail_on_error: false  # Do not fail CI if there are errors
          reporter: github-pr-review  # PR review action that adds code review annotations
          github_token: ${{ secrets.github_token }}  # Invalid after the test is finished


      - uses: pre-commit/action@v3.0.0
        name: Run pre-commit hooks with basic trailing-whitespace checks and pytest
        if: ${{ matrix.python-version != '2.7' }}
        with:
          # The --hook-stage manual only runs the stages that add the manual keyword in
          # .pre-commit-config.yaml. Currently that's simple white space checks and pytest:
          extra_args: --all-files --verbose --hook-stage manual

      - name: Run Pytest for python 2 and get code coverage for Codecov
        if: ${{ matrix.python-version == '2.7' }}
        run: >
          pip install enum future mock pytest-coverage pytest-mock &&
          pytest --cov-fail-under=10
          --cov=scripts --cov=ocaml/xcp-rrdd
          scripts/ ocaml/xcp-rrdd -vv -ra
          --cov-report xml:.git/coverage.xml
        env:
          PYTHONDEVMODE: yes

      - name: Upload Python ${{matrix.python-version}} coverage report to Codecov
        uses: codecov/codecov-action@v3
        # Upload the .git/coverage.xml file created by --cov-report xml:.git/coverage.xml
        # created by pytest --cov-report xml:.git/coverage.xml above and the pytest config
        # in xen-api.git/pyproject.toml and .pre-commit-config.yaml in the pre-commit hook.
        with:
          directory: .git
          files: coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          flags: python${{matrix.python-version}}
          name: coverage${{matrix.python-version}}
          verbose: true

      # pylint is also added as a pre-commit hook in .pre-commit-config.yaml
      # but we also run it here to get annotations in the pull request code review
      # in case the pre-commit hook is not run by the developer:
      - uses: dciborow/action-pylint@0.1.1
        if: ${{ matrix.python-version != '2.7' }}
        with:
          reporter: github-pr-review
          # Disable import errors and comments that are for later clean-up stages, but
          # not for the 1st stage of porting the code to Python 3.6 and reviewing the
          # changes closely in the pull request code review:
          pylint_args: --disable=import-error --disable=C
          # Do not fail CI if there are errors, because most warnings are not errors
          # but we want to see them in the pull request code review in case a potentially
          # a warning that could be serious is missed by the developer, like if open()
          # without encoding is used in Python 3.6 in a XAPI plugin where the locale
          # us not set to an UTF-8 locale. If in such situation the opened file deals
          # with UTF-8 characters, the code will fail in Python 3.6 but not in Python 2.7.
          # and also not in 3.7 and later (as these have an UTF-8 mode that gets enabled).
          fail_on_error: false
          level: warning
          # To be customized to cover remaining Python scripts:
          glob_pattern: "**/*.py"

  ocaml-tests:
    name: Run OCaml tests
    runs-on: ubuntu-20.04
    env:
      # Ensure you also update test-sdk-builds
      # when changing this value, to keep builds
      # consistent
      XAPI_VERSION: "v0.0.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup XenAPI environment
        uses: ./.github/workflows/setup-xapi-environment
        with:
          xapi_version: ${{ env.XAPI_VERSION }}

      - name: Build
        run: opam exec -- make

      - name: Run tests
        run: opam exec -- make test

      - name: Check all code
        run: opam exec -- make check

      - name: Run stress tests
        run: opam exec -- make stresstest
        if: ${{ github.event_name == 'schedule' }}

      - name: Make install smoketest
        run: |
          opam exec -- make install DESTDIR=$(mktemp -d)
          opam exec -- make install DESTDIR=$(mktemp -d) BUILD_PY2=NO

      - name: Check disk space
        run: df -h || true

      - name: Cleanup XenAPI environment
        uses: ./.github/workflows/cleanup-xapi-environment

  deprecation-test:
    name: Deprecation tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate empty configuration for make to be happy
        run: touch config.mk

      - name: quality-gate
        run: make quality-gate

      - name: pyflakes
        uses: reviewdog/action-pyflakes@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error

  test-sdk-builds:
    name: Test SDK builds
    uses: ./.github/workflows/generate-and-build-sdks.yml
    with:
      # Ensure you also update ocaml-tests
      # when changing this value, to keep builds
      # consistent
      xapi_version: "v0.0.0"
